name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
       - name: "first wf"
         run: |
          echo "hello world"
          echo "Done - Goodbye"
